set(_CATKIN_CURRENT_PACKAGE "plumbing_test_turtle")
set(plumbing_test_turtle_VERSION "0.0.0")
set(plumbing_test_turtle_MAINTAINER "zzy <zzy@todo.todo>")
set(plumbing_test_turtle_PACKAGE_FORMAT "2")
set(plumbing_test_turtle_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "turtlesim")
set(plumbing_test_turtle_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(plumbing_test_turtle_BUILDTOOL_DEPENDS "catkin")
set(plumbing_test_turtle_BUILDTOOL_EXPORT_DEPENDS )
set(plumbing_test_turtle_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "turtlesim")
set(plumbing_test_turtle_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "turtlesim")
set(plumbing_test_turtle_TEST_DEPENDS )
set(plumbing_test_turtle_DOC_DEPENDS )
set(plumbing_test_turtle_URL_WEBSITE "")
set(plumbing_test_turtle_URL_BUGTRACKER "")
set(plumbing_test_turtle_URL_REPOSITORY "")
set(plumbing_test_turtle_DEPRECATED "")